### ISSUE TITLE
can you offer more detail docs and source codes about the gym？

### ISSUE THREAD

**Issue by Fantasticer** [intrig-unicamp/gym#1]

**Comment by raphaelvrosa** [comment]
Hi, 
The project was supported by a company, and currently we are struggling with the open source request to release the code. The idea is to create repos for code, results, etc. 

For now we got papers based on Gym experiments:
- https://www.dropbox.com/s/n9niziuhi648scj/2017-rosa-taking.pdf?dl=0

- http://ieeexplore.ieee.org/document/8030496/
Preprint at: https://www.dropbox.com/s/2av3tkdzrx0adyz/2017-09-commag-gym-preprint.pdf?dl=0

**Comment by marialubeznov** [comment]
Hello! Do you have any update regrading the status of making Gym open source? Thanks!

**Comment by raphaelvrosa** [comment]
Sorry for being late, too much on the table lately. Now it's open source, I hope you enjoy!
